### PR TITLE
Fix error message for FetchRemoteDataSniff

### LINKED ISSUE #243: WordPressVIPMinimum.VIP.FetchingRemoteData.fileGetContentsUknown buggy error message
## Bug Description
Seeing a buggy error message here:

> %s() is uncached. If this is being used to query a remote file please use wpcom_vip_file_get_contents() instead. If it\'s used for a local file please use WP_Filesystem instead. Read more here: **https://vip.wordpress.com/documentation/using-wp_filesystem-instead-of-direct-file-access-functions/** 

stemming from the sniff `WordPressVIPMinimum.VIP.FetchingRemoteData.fileGetContentsUknown` when it detects `file_get_contents()`

## Tested Against `master` branch?

- [x] I have verified the issue still exists in the `master` branch of VIPCS.

### PR DESCRIPTION
**Pull request by rebeccahum**
Fixes #243.

Also uses `addWarning()` without `sprintf()` since that's improper.

### CODE REVIEW

File: WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php [hunk 1]
```diff
@@ -728,8 +728,7 @@ protected function checkForFunctionPrototype(
 				// We haven't been defined by this point.
 				$phpcsFile->addWarning( "Variable `%s` is undefined.", $stackPtr,
 					'UndefinedVariable',
-					array( "\${$varName}" ),
-					'WordPressVIPMinimum.Variables.VariableAnalysis'
+					array( "\${$varName}" )
```
Comment (GaryJones) [inline WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php]: These changes were already merged via a different PR. Please pull `master` into this PR's branch, so that we don't re-commit the changes and possibly lose the commit message and reference from the first effort.

File: WordPress-VIP-Go/ruleset.xml [hunk 2]
```diff
@@ -50,7 +50,6 @@
 	<rule ref="WordPressVIPMinimum.VIP.FetchingRemoteData.fileGetContentsUknown">
 		<type>error</type>
 		<Severity>5</Severity>
-		<message>%s() is uncached. If this is being used to query a remote file please use wpcom_vip_file_get_contents() instead. If it's used for a local file please use WP_Filesystem instead. Read more here: https://vip.wordpress.com/documentation/using-wp_filesystem-instead-of-direct-file-access-functions/</message>
```
Comment (GaryJones) [inline WordPress-VIP-Go/ruleset.xml]: This contains a documentation link that isn't present in the message in the sniff. Is it still of value to keep the link, either in the sniff (for WPCOM + Go), or this ruleset (just Go)?

Comment (rebeccahum) [reply WordPress-VIP-Go/ruleset.xml]: I don't think it's of value to keep the link since it's marked as "VIP Go Platform Specific".  If anything, I'm thinking that we should use https://codex.wordpress.org/Filesystem_API.
