### PR TITLE
Hide catching exceptions

### LINKED ISSUE #114: Unused variable $e.
We really should not report on `$e` in try...catch

```
} catch ( Exception $e ) {
```

### PR DESCRIPTION
**Pull request by rebeccahum**
Fixes #114. This is a reboot of #144.

### CODE REVIEW

File: WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.php [hunk 1]
```diff
@@ -31,9 +31,16 @@ public function getErrorList() {
 	 * @return array <int line number> => <int number of warnings>
 	 */
 	public function getWarningList() {
-		return array(
+		$warningList = [
 			5 => 2,
-		);
+		];
+	
+ 		// PHP prior to version 7.x does not properly process the $e.
```
Comment (GaryJones) [inline WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.php]: There's a leading space at the start of this line.

File: WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.php [hunk 2]
```diff
@@ -31,9 +31,16 @@ public function getErrorList() {
...
+		if ( true === version_compare( PHP_VERSION, '7.0.0', '>' ) ) {
+			$warningList[18] = 2;
+		}
+
+ 		return $warningList;
```
Comment (GaryJones) [inline WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.php]: There's a leading space at the start of this line.

File: WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.php [hunk 3]
```diff
@@ -31,9 +31,16 @@ public function getErrorList() {
...
 	 */
 	public function getWarningList() {
-		return array(
+		$warningList = [
 			5 => 2,
-		);
+		];
+	
+ 		// PHP prior to version 7.x does not properly process the $e.
+		if ( true === version_compare( PHP_VERSION, '7.0.0', '>' ) ) {
```
Comment (GaryJones) [inline WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.php]: Should this be `'>='`, so that it matches exactly `7.0.0` as well?

File: WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.php (hunk 1 above)
Comment (GaryJones) [reply WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.php]: Is there any reference that could be added, to find out more about why it doesn't properly process the `$e`?

Could the code that does the processing be updated, so it does?

Comment (rebeccahum) [reply WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.php]: With VIP running a later version, would it even be applicable to check that PHP is < 7?

Comment (GaryJones) [reply WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.php]: This repo supports [down to PHP 5.6](https://github.com/Automattic/VIP-Coding-Standards/blob/master/composer.json#L18) (related: https://github.com/Automattic/VIP-Coding-Standards/issues/211).

Until the level is raised to 7.0+ (or later), then yes, it should be checked.

The version that these sniffs are run at, and the version that the code is expected to run at, can be two different versions.

Comment (rebeccahum) [reply WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.php]: > Is there any reference that could be added, to find out more about why it doesn't properly process the $e?

I couldn't find any reference on _why_ and speaking to @david-binda, he doesn't recall why either.

Comment (rebeccahum) [reply WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.php]: Update: I don't believe this is an issue anymore since it appears that the version check was added because it was failing the tests.
