### PR TITLE
IncludingFileSniff: Add get_parent_theme_file_path to safelist

### LINKED ISSUE #462: get_parent_theme_file_path() is not a custom function
## Bug Description
`get_parent_theme_file_path()` is not a custom function and therefore shouldn't be flagged as one: https://developer.wordpress.org/reference/functions/get_parent_theme_file_path/
```
  48 | WARNING | File inclusion using custom function ( `get_parent_theme_file_path()` ). Must return local file source, as external URLs are prohibited on WordPress VIP. Probably needs manual inspection.
```

## Minimal Code Snippet

```php
require_once get_parent_theme_file_path( "/includes/blocks/file.php" );
```

## Error Code

WordPressVIPMinimum.Files.IncludingFile.UsingCustomFunction

## Environment

Use `php -v` and `composer show` to get versions.

| Question                | Answer
| ------------------------| -------
| PHP version             | x.y.z 
| PHP_CodeSniffer version | x.y.z
| VIPCS version           | x.y.z

## Tested Against `master` branch?

- [x] I have verified the issue still exists in the `master` branch of VIPCS.

### PR DESCRIPTION
**Pull request by rebeccahum**
Fixes #462.

### CODE REVIEW

File: WordPressVIPMinimum/Sniffs/Files/IncludingFileSniff.php [hunk 1]
```diff
@@ -31,6 +31,7 @@ class IncludingFileSniff extends AbstractFunctionRestrictionsSniff {
 		'get_stylesheet_directory',
 		'get_template_directory',
 		'locate_template',
+		'get_parent_theme_file_path'
```
Comment (GaryJones) [inline WordPressVIPMinimum/Sniffs/Files/IncludingFileSniff.php]:
```suggestion
		'get_parent_theme_file_path',
```

**Comment by GaryJones** [comment]
Needs unit tests.

**Comment by rebeccahum** [comment]
@GaryJones Thanks for the reminder! Done.
