### PR TITLE
Ignore return values when a filter callback is abstract

### LINKED ISSUE #580: Sniff WordPressVIPMinimum.Hooks.AlwaysReturnInFilter.MissingReturnStatement fails on abstract methods
## Bug Description

If you define an abstract class that sets up a filter in its constructor and sets the callback to an abstract method in the class which will be defined by implementing classes, the `WordPressVIPMinimum.Hooks.AlwaysReturnInFilter.MissingReturnStatement` sniff causes phpcs to crash, because it's trying to evaluate the return statement in an abstract method.

The specific error message being returned is this:

```
An error occurred during processing; checking has been aborted. The error message was: Undefined index: scope_opener in /path/to/.composer/vendor/automattic/vipwpcs/WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php on line 194 (Internal.Exception)
```

## Minimal Code Snippet

```php
abstract class good_example_abstract_class { // Ok.
	public function __construct() {
		add_filter( 'good_example_class_filter', [ $this, 'class_filter' ] );
	}

	abstract public function class_filter( $param );
}

class good_example_abstract_class_implementation { // Ok.
	public function class_filter( $param ) {
		if ( 1 === 1 ) {
			if ( 1 === 0 ) {
				return 'whoops';
			} else {
				return 'here!';
			}
		}
		return 'This is Okay';
	}
}
```

## Error Code

No error code should be triggered.

## Environment

Use `php -v` and `composer show` to get versions.

| Question                | Answer
| ------------------------| -------
| PHP version             | 7.3.0 
| PHP_CodeSniffer version | 3.5.6
| VIPCS version           | 2.2.0

## Additional Context (optional)

Fixed in PR #581 

## Tested Against `master` branch?

- [X] I have verified the issue still exists in the `master` branch of VIPCS.
- [X] I have verified the issue still exists in the `develop` branch of VIPCS.

### PR DESCRIPTION
**Pull request by kevinfodness**
If a filter is defined in the constructor of an abstract class, and uses an abstract method as its callback, relying on implementing classes to define the return value, the `WordPressVIPMinimum.Hooks.AlwaysReturnInFilter.MissingReturnStatement` sniff causes phpcs to crash.

This PR adds a unit test to confirm the issue, and implements a fix using the same code that is used by phpcs itself.

Fixes #580

### CODE REVIEW

File: WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php [hunk 1]
```diff
@@ -175,6 +175,15 @@ private function processFunction( $stackPtr, $start = 0, $end = null ) {
 	 */
 	private function processFunctionBody( $stackPtr ) {
 
+		/**
+		 * Stop if the constructor doesn't have a body, like when it is abstract.
+		 *
+		 * @see https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Generic/Sniffs/NamingConventions/ConstructorNameSniff.php#L87-L90
+		 */
+		if ( false === isset( $this->tokens[ $stackPtr ]['scope_closer'] ) ) {
```
Comment (GaryJones) [inline WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php:183]:
```suggestion
		if ( isset( $this->tokens[ $stackPtr ]['scope_closer'] ) === false ) {
```

File: WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php [hunk 2]
```diff
@@ -175,6 +175,15 @@ private function processFunction( $stackPtr, $start = 0, $end = null ) {
 	 */
 	private function processFunctionBody( $stackPtr ) {
 
+		/**
+		 * Stop if the constructor doesn't have a body, like when it is abstract.
```
Comment (GaryJones) [inline WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php:179]:
```suggestion
		 * Stop if the function doesn't have a body, like when it is abstract.
```

**Comment by jrfnl** [comment]
I've added two additional commits to this PR, updating the unit tests and implementing my suggestion from https://github.com/Automattic/VIP-Coding-Standards/issues/580#issuecomment-689119006

File: WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php [hunk 3]
```diff
@@ -175,12 +175,18 @@ private function processFunction( $stackPtr, $start = 0, $end = null ) {
...
 
-		/**
-		 * Stop if the function doesn't have a body, like when it is abstract.
-		 *
-		 * @see https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Generic/Sniffs/NamingConventions/ConstructorNameSniff.php#L87-L90
-		 */
-		if ( isset( $this->tokens[ $stackPtr ]['scope_closer'] ) === false ) {
+		$filterName = $this->tokens[ $this->filterNamePtr ]['content'];
+
+		$methodProps = $this->phpcsFile->getMethodProperties($stackPtr);
```
Comment (GaryJones) [inline WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php:180]:
```suggestion
		$methodProps = $this->phpcsFile->getMethodProperties( $stackPtr );
```

File: WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php [hunk 4]
```diff
@@ -175,12 +175,18 @@ private function processFunction( $stackPtr, $start = 0, $end = null ) {
...
+		if ($methodProps['is_abstract'] === true) {
```
Comment (GaryJones) [inline WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php:181]:
```suggestion
		if ( $methodProps['is_abstract'] === true ) {
```

**Comment by GaryJones** [comment]
Noting that the new Warning will now appear when there was no warning previously (which was a false negative due to the lack of support for short array syntax).

**Comment by jrfnl** [comment]
> Noting that the new Warning will now appear when there was no warning previously (which was a false negative due to the lack of support for short array syntax).

Correct. I've also given it a separate error code on purpose with that in mind. Semver-wise, it should probably go into a minor rather than a patch version as it can be seen as a new feature.

File: WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php [hunk 5]
```diff
@@ -175,6 +175,21 @@ private function processFunction( $stackPtr, $start = 0, $end = null ) {
 	 */
 	private function processFunctionBody( $stackPtr ) {
 
+		$filterName = $this->tokens[ $this->filterNamePtr ]['content'];
+
+		$methodProps = $this->phpcsFile->getMethodProperties( $stackPtr );
+		if ( $methodProps['is_abstract'] === true ) {
+			$message = 'The callback for the `%s` filter hook-in points to an abstract method. Please, make sure that all child class implementations of this abstract method always return a value.';
```
Comment (rebeccahum) [inline WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php:182]:
```suggestion
			$message = 'The callback for the `%s` filter hook-in points to an abstract method. Please ensure that child class implementations of this abstract method always return a value.';
```

**Review by rebeccahum — CHANGES_REQUESTED** [review]

**Review by GaryJones — APPROVED** [review]

**Review by rebeccahum — APPROVED** [review]
