### PR TITLE
Inspections: Multiple fixes

### LINKED ISSUE #394: pre_get_posts filter should not be flagged to return value
## Bug Description

```
Warning: Please, make sure that a callback to 'pre_get_posts' filter is always returning some value.
```

Since it's an action and the argument is passed by reference, return is not necessary.

## Minimal Code Snippet

```php
<?php 

add_filter( 'pre_get_posts', 'test_function' );

function test_function( $test ) {
	// Do something.
}
```

## Error Code

`WordPressVIPMinimum.Hooks.AlwaysReturnInFilter.MissingReturnStatement`

## Tested Against `master` branch?

- [x] I have verified the issue still exists in the `master` branch of VIPCS.

### PR DESCRIPTION
**Pull request by GaryJones**
- Add strict comparisons
- Added missing scope keywords
- Added parentheses to clarify one specific conditional
- Consolidate multiple `isset()` calls
- Consolidate positive nested `if()`’s
- Fix difference in case for function calls
- Simplify return statements
- Switch to __DIR__
- Switched FQCN to import statements
- Use static property
- Use more performant `strpos()` instead of `substr()`
- Split or remove `else` / `elseif` workflows for lower complexity and more comprehension
- Remove misuse of `array_push()`
- Remove misuse of `array_values()`
- Remove misuse of `in_array()`
- Remove useless `return`
- Remove redundant `continue`
- Removed comments that were naming parameters
- Remove default assignments of `null` to class properties
- Remove function parameters that match default arg values
- Remove redundant parentheses

This should be the bulk of the inspections now completed, so marking this as fixes #394.

### CODE REVIEW

File: WordPressVIPMinimum/Sniffs/JS/StringConcatSniff.php [hunk 1]
```diff
@@ -52,22 +52,18 @@ public function register() {
...
 
-		$prevToken = $phpcsFile->findPrevious( Tokens::$emptyTokens, ( $stackPtr - 1 ), null, true, null, true );
+		$prevToken = $phpcsFile->findPrevious( Tokens::$emptyTokens, $stackPtr - 1, null, true, null, true );
 
-		if ( T_CONSTANT_ENCAPSED_STRING === $tokens[ $prevToken ]['code'] ) {
-			if ( false !== strpos( $tokens[ $prevToken ]['content'], '<' ) && 1 === preg_match( '/\<[a-zA-Z]+/', $tokens[ $prevToken ]['content'] ) ) {
-				$data = [ $tokens[ $nextToken ]['content'] . '+' ];
-				$this->addFoundError( $phpcsFile, $stackPtr, $data );
-			}
+		if ( ( T_CONSTANT_ENCAPSED_STRING === $tokens[ $prevToken ]['code'] ) && false !== strpos( $tokens[ $prevToken ]['content'], '<' ) && 1 === preg_match( '/\<[a-zA-Z]+/', $tokens[ $prevToken ]['content'] ) ) {
```
Comment (rebeccahum) [inline WordPressVIPMinimum/Sniffs/JS/StringConcatSniff.php]: Should we remove the extra set of brackets enclosing `T_CONSTANT_ENCAPSED_STRING === $tokens[ $prevToken ]['code']`?

File: WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php [hunk 2]
```diff
@@ -201,10 +201,8 @@ public function process_parameters( $stackPtr, $group_name, $matched_content, $p
 		switch ( $matched_content ) {
 			case 'show_admin_bar':
 				$error = true;
-				if ( true === $this->remove_only ) {
-					if ( 'true' === $parameters[1]['raw'] ) {
-						$error = false;
-					}
+				if ( ( true === $this->remove_only ) && 'true' === $parameters[1]['raw'] ) {
```
Comment (rebeccahum) [inline WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php]: Should we remove the extra set of brackets enclosing `true === $this->remove_only`?

File: WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php [hunk 3]
```diff
@@ -215,10 +213,8 @@ public function process_parameters( $stackPtr, $group_name, $matched_content, $p
 				}
 
 				$error = true;
-				if ( true === $this->remove_only && isset( $parameters[2]['raw'] ) ) {
-					if ( '__return_true' === $this->strip_quotes( $parameters[2]['raw'] ) ) {
-						$error = false;
-					}
+				if ( true === $this->remove_only && isset( $parameters[2]['raw'] ) && '__return_true' === $this->strip_quotes( $parameters[2]['raw'] ) ) {
```
Comment (rebeccahum) [inline WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php]: Should we remove the extra set of brackets enclosing `true === $this->remove_only && isset( $parameters[2]['raw']`?

File: WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php [hunk 4]
```diff
@@ -307,14 +303,12 @@ public function process_text_for_style( $stackPtr, $file_name ) {
...
-					if ( true === $this->remove_only ) {
-						// Check the value of the CSS property.
-						if ( preg_match( '`' . preg_quote( $property, '`' ) . '\s*:\s*(.+?)\s*(?:!important)?;`', $content, $matches ) > 0 ) {
-							$value = trim( $matches[1] );
-							$valid = $this->validate_css_property_value( $value, $requirements['type'], $requirements['value'] );
-							if ( true === $valid ) {
-								$error = false;
-							}
+					// Check the value of the CSS property.
+					if ( ( true === $this->remove_only ) && preg_match( '`' . preg_quote( $property, '`' ) . '\s*:\s*(.+?)\s*(?:!important)?;`', $content, $matches ) > 0 ) {
```
Comment (rebeccahum) [inline WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php]: Should we remove the extra set of brackets enclosing `true === $this->remove_only`?

File: WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php [hunk 5]
```diff
@@ -641,19 +635,16 @@ function findFunctionCall(
...
 		$tokens = $phpcsFile->getTokens();
 
 		// Slight hack: also allow this to find args for array constructor.
 		// TODO: probably should refactor into three functions: arg-finding and bracket-finding
-		if ( ( $tokens[$stackPtr]['code'] !== T_STRING) && ( $tokens[$stackPtr]['code'] !== T_ARRAY) ) {
-			// Assume $stackPtr is something within the brackets, find our function call
-			if ( ( $stackPtr = $this->findFunctionCall( $phpcsFile, $stackPtr ) ) === false ) {
-				return false;
-			}
+		if ( ( $tokens[ $stackPtr ]['code'] !== T_STRING ) && ( $tokens[ $stackPtr ]['code'] !== T_ARRAY ) && ( $stackPtr = $this->findFunctionCall( $phpcsFile, $stackPtr ) ) === false ) {
```
Comment (rebeccahum) [inline WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php]: Should we remove the brackets enclosing all the expressions to be evaluated?

File: WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php (hunk 3 above)
Comment (GaryJones) [reply WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php]: I don't think this observation is valid.
